export const typeConst = {
  LOGIN: 'login',
  FORGOT_PASS: 'FORGOT_PASS',
  VERIFY_OTP: 'VERIFY_OTP',
  SIGNUP: 'SIGNUP',
  HOME: 'HOME',
  TRUCK_DETAILS: 'TRUCK_DETAILS',
  ADD_ASSIGNMENT: 'ADD_ASSIGNMENT',
  SCHEDULE: 'SCHEDULE',
  PICKUP: 'PICKUP',
  DELIVERY: 'DELIVERY'
};
